### ISSUE TITLE
12版本安装不上

### ISSUE THREAD

**Issue by chenguoliang318** [chanvi/odoo_wechat_corp#3]
12安装时报错，odoo.tools.convert.ParseError: "Cannot update missing record 'auth_oauth.wechat'" while parsing None:4, near
<data inherit_id="web.login" name="OAuth Login Wechat">
            <xpath expr="//button[@type='submit']" position="before">
                <div class="pull-right">
                    <a class="btn btn-link" href="/wechat/open/">企业微信登陆</a>
                </div>
            </xpath>
        </data>

**Comment by chanvi** [comment]
for odoo10, odoo11
